parser: "babel-eslint"

env:
  es6: true

parserOptions:
  ecmaFeatures:
    jsx: true

plugins:
  - react
  - react-native

extends: "plugin:react/recommended"

rules:
  indent:
    - 2
    - 2

  linebreak-style:
    - 2
    - unix

  quotes:
    - 2
    - single

  semi:
    - 2
    - always
